let str="                   akshat                      ";
console.log(str.trim());
let str1="Akshat Verma";
console.log(str1.toUpperCase());
let str2="string";
console.log(str2.indexOf("u"));
let str3="       study     ";
console.log(str3.trim().toUpperCase());
let str5="lakku";
console.log(str5.slice(-3));
let str6="verma";
console.log(str6.replace("er","m"));
let str7="akshat ";
console.log(str7.repeat(10));