let body = document.querySelector("body");
let container = document.createElement("div");
body.append(container);
container.innerText="Akshat Verma";
container.innerText="";
let red = document.createElement("p");
container.prepend(red);
red.innerText="I am Red";
// console.dir(red.style);
red.style.color="red";
let heading = document.createElement("h1");
container.append(heading);
heading.innerText="I am Blue Color";
heading.style.color="blue";
let secondDiv = document.createElement("div");
container.append(secondDiv);
let headingUnder_sd = document.createElement("h1");
secondDiv.appendChild(headingUnder_sd);
headingUnder_sd.innerText="I am Div";
let paraUnder_secondDiv = document.createElement("p");
secondDiv.appendChild(paraUnder_secondDiv);
paraUnder_secondDiv.innerText="ME Too!";
secondDiv.style.border="2px solid black";